### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by LorenzoFioroni** [albertomercurio/QuantumToolbox-Benchmarks#1]
There is a typo in the "_introduction_" lecture. Specifically, [you write "_lloking_" instead of "_looking_"
](https://albertomercurio.github.io/Lectures/QuantumToolbox.jl/introduction.html#:~:text=However%2C%20I%20was-,lloking,-for%20a%20more)
I hope this problem will be fixed as soon as possible.

@albertomercurio thanks for your help, 
Lorenzo

**Comment by albertomercurio** [comment]
Grazie compá
